
DROP TABLE Specii_Inrudite CASCADE CONSTRAINTS;
DROP TABLE Dusmani_Naturali CASCADE CONSTRAINTS;
DROP TABLE Imagini_Animale CASCADE CONSTRAINTS;

DROP TABLE Animale CASCADE CONSTRAINTS;

DROP TABLE Administratori CASCADE CONSTRAINTS;
DROP TABLE Utilizatori CASCADE CONSTRAINTS;

DROP TABLE Origini CASCADE CONSTRAINTS;
DROP TABLE Regimuri_Alimentare CASCADE CONSTRAINTS;
DROP TABLE Clase_Animale CASCADE CONSTRAINTS;
DROP TABLE Statute_Conservare CASCADE CONSTRAINTS;
DROP TABLE Clime CASCADE CONSTRAINTS;
DROP TABLE Moduri_Inmultire CASCADE CONSTRAINTS;


DROP SEQUENCE secv_origini;
DROP SEQUENCE secv_regimuri;
DROP SEQUENCE secv_clase;
DROP SEQUENCE secv_statute;
DROP SEQUENCE secv_clime;
DROP SEQUENCE secv_inmultire;
DROP SEQUENCE secv_animale;
DROP SEQUENCE secv_imagini;
DROP SEQUENCE secv_admini;
DROP SEQUENCE seq_utilizatori_id;


DROP TRIGGER trg_utilizatori_id;